FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 5000

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["ContentApi.csproj", "./"]
RUN dotnet restore "ContentApi.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "ContentApi.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ContentApi.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENV ASPNETCORE_ENVIRONMENT=Development
ENTRYPOINT ["dotnet", "ContentApi.dll"]
